name: Docker Build
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["7.0"]
    name: build ${{ matrix.php }} images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: current directory
        run: |
          pwd
          ls -la
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push php-fpm:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm64
          tags: craftcms/php-fpm:${{ matrix.php }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}
      - name: Build and push php-fpm:${{ matrix.php }}-dev
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/dev.Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm64
          tags: craftcms/php-fpm:${{ matrix.php }}-dev
          build-args: |
            PROJECT_TYPE=php-fpm
            PHP_VERSION=${{ matrix.php }}
      - name: Build and push nginx:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm64
          tags: craftcms/php-fpm:${{ matrix.php }}-dev
          build-args: |
            PHP_VERSION=${{ matrix.php }}
